// List actions
export const LOAD_LIST = 'LOAD_LIST';
export const SORT_LIST = 'SORT_LIST';
export const SEARCH_LIST = 'SEARCH_LIST';
export const FILTER_LIST_STATUS = 'FILTER_LIST_STATUS';
export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';
export const UPDATE_LIST_ITEM = 'UPDATE_LIST_ITEM';
export const UPDATE_CURRENT_LIST_NAME = 'UPDATE_CURRENT_LIST_NAME';
export const SWITCH_LIST_FAILURE = 'SWITCH_LIST_FAILURE';
export const SWITCH_SYNCER = 'SWITCH_SYNCER';
export const SWITCH_SYNCER_FAILURE = 'SWITCH_SYNCER_FAILURE';
export const SYNC_LIST = 'SYNC_LIST';
export const UPDATE_HEADER_ORDER = 'UPDATE_HEADER_ORDER';

// Search actions
export const SHOW_SEARCH_REQUEST = 'SHOW_SEARCH_REQUEST';
export const SHOW_SEARCH_FAILURE = 'SHOW_SEARCH_FAILURE';
export const SHOW_SEARCH_SUCCESS = 'SHOW_SEARCH_SUCCESS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const SET_SEARCH_SORTBY = 'SET_SEARCH_SORTBY';

// Series actions
export const SHOW_SERIES_REQUEST = 'SHOW_SERIES_REQUEST';
export const SHOW_SERIES_SUCCESS = 'SHOW_SERIES_SUCCESS';
export const SHOW_SERIES_FAILURE = 'SHOW_SERIES_FAILURE';
export const LOAD_SERIES_EPISODES_REQUEST = 'LOAD_SERIES_EPISODES_REQUEST';
export const LOAD_SERIES_EPISODES_SUCCESS = 'LOAD_SERIES_EPISODES_SUCCESS';
export const LOAD_SERIES_EPISODES_FAILURE = 'LOAD_SERIES_EPISODES_FAILURE';
export const HIDE_SERIES = 'HIDE_SERIES';

// Kicker actions
export const SCROBBLE_REQUEST = 'SCROBBLE_REQUEST';
export const SCROBBLE_SUCCESS = 'SCROBBLE_SUCCESS';
export const SCROBBLE_CLEAR = 'SCROBBLE_CLEAR';

// Explore actions
export const SHOW_COLLECTIONS_REQUEST = 'SHOW_COLLECTIONS_REQUEST';
export const SHOW_COLLECTIONS_FAILURE = 'SHOW_COLLECTIONS_FAILURE';
export const SHOW_COLLECTIONS_SUCCESS = 'SHOW_COLLECTIONS_SUCCESS';
export const SHOW_FEATURED_REQUEST = 'SHOW_FEATURED_REQUEST';
export const SHOW_FEATURED_FAILURE = 'SHOW_FEATURED_FAILURE';
export const SHOW_FEATURED_SUCCESS = 'SHOW_FEATURED_SUCCESS';

// Calendar actions
export const LOAD_CALENDAR_REQUEST = 'LOAD_CALENDAR_REQUEST';
export const LOAD_CALENDAR_FAILURE = 'LOAD_CALENDAR_FAILURE';
export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCESS';

// Season charts
export const LOAD_CHART_REQUEST = 'LOAD_CHART_REQUEST';
export const LOAD_CHART_FAILURE = 'LOAD_CHART_FAILURE';
export const LOAD_CHART_SUCCESS = 'LOAD_CHART_SUCCESS';
export const SWITCH_SEASON = 'SWITCH_SEASON';

// RSS actions
export const SHOW_RSS_REQUEST = 'SHOW_RSS_REQUEST';
export const SHOW_RSS_FAILURE = 'SHOW_RSS_FAILURE';
export const SHOW_RSS_SUCCESS = 'SHOW_RSS_SUCCESS';
export const SWITCH_RSS_URL = 'SWITCH_RSS_URL';
export const INVALID_RSS_URL = 'INVALID_RSS_URL';

// Toast
export const CREATE_TOAST = 'CREATE_TOAST';
export const DESTROY_TOAST = 'DESTROY_TOAST';
export const UPDATE_TOAST = 'UPDATE_TOAST';
